# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_is_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_path',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
    ]
