# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_song_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='logo_path',
        ),
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(upload_to=b''),
        ),
    ]
