# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='logo_path',
            field=models.CharField(default=4, max_length=5000),
            preserve_default=False,
        ),
    ]
